# Using latest Homebrew
# update

# Update already-installed formula
# upgrade

# Tap any repository
tap phinze/cask       # to install brew-cask
tap homebrew/versions # to install any library
tap homebrew/dupes    # to install apple-gcc42
tap homebrew/binary   # to install packer
tap homebrew/science  # to install R

# Packages
install apple-gcc42 || true
install bash        || true
install brew-cask   || true
install ctags       || true
install fontforge   || true
install gfortran    || true
install git         || true
install imagemagick || true
install mysql       || true
install nkf         || true
install openssl     || true
install packer      || true
install R           || true
install readline    || true
install reattach-to-user-namespace || true
install tmux        || true
install tree        || true
install unrar       || true
install wget        || true
install zsh         || true
install z           || true

# Package for dmg


# Remove outdated versions from the cellar
cleanup
