FROM ubuntu:16.04

RUN apt-get -qq update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd

RUN sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config && \
    sed -ri 's/PermitEmptyPasswords no/PermitEmptyPasswords yes/g' /etc/ssh/sshd_config

RUN passwd -d root

WORKDIR /home/root

EXPOSE 22

CMD ["/usr/sbin/sshd", "-E", "/var/log/sshd", "-D"]
