include_recipe "../cookbooks/homebrew/default"
include_recipe "../cookbooks/zsh/default"
# include_recipe "cookbooks/emacs/default"
include_recipe "../cookbooks/bundle/default"
include_recipe "../cookbooks/gemrc/default"
include_recipe "../cookbooks/gitconfig/default"
include_recipe "../cookbooks/gitignore/default"
include_recipe "../cookbooks/hammerspoon/default"
include_recipe "../cookbooks/irbrc/default"
include_recipe "../cookbooks/nodebrew/default"
include_recipe "../cookbooks/pyenv/default"
include_recipe "../cookbooks/rbenv/default"
include_recipe "../cookbooks/tmux/default"
include_recipe "../cookbooks/peco/default"
# include_recipe "cookbooks/osx_defaults/default"
# include_recipe "cookbooks/vichrome/default"
# include_recipe "cookbooks/iterm2/default"
