include_recipe "../cookbooks/homebrew/default"
include_recipe "../cookbooks/git/default"
include_recipe "../cookbooks/zsh/default"
include_recipe "../cookbooks/alacritty/default"
include_recipe "../cookbooks/aws/default"
include_recipe "../cookbooks/emacs/default"
include_recipe "../cookbooks/bundle/default"
include_recipe "../cookbooks/config/default"
include_recipe "../cookbooks/gemrc/default"
include_recipe "../cookbooks/gitconfig/default"
include_recipe "../cookbooks/gitignore/default"
include_recipe "../cookbooks/hammerspoon/default"
include_recipe "../cookbooks/irbrc/default"
# include_recipe "../cookbooks/nodebrew/default"
include_recipe "../cookbooks/pyenv/default"
include_recipe "../cookbooks/rbenv/default"
include_recipe "../cookbooks/tmux/default"
include_recipe "../cookbooks/peco/default"
include_recipe "../cookbooks/osx_defaults/default"
include_recipe "../cookbooks/starship/default"
include_recipe "../cookbooks/packages/essential"
# include_recipe "../cookbooks/packages/develop" # NOTE: Too slow. If you execute, commentin this line
# include_recipe "../cookbooks/vichrome/default"
# include_recipe "../cookbooks/whalebrew/default"
# include_recipe "../cookbooks/iterm2/default"
# kotori, Forcus on TO-DO, cooViewer, MKPlayer
