[General]
  snippetfile = "/Users/hiromu.mogi/.config/pet/snippet.toml"
  editor = "emacsclient -nw"
  column = 40
  selectcmd = "fzf"

[Gist]
  file_name = "pet-snippet.toml"
  access_token = "<Get access_token from GitHub>"
  gist_id = "<Get snippet gist id>"
  public = false
  auto_sync = false
