[General]
  snippetfile = "~/.config/pet/pet-snippet.toml"
  editor = "vi"
  column = 40
  selectcmd = "fzf"
  backend = "gist"

[Gist]
  access_token = "<Get access_token from GitHub>"
  gist_id = "<Get snippet gist id>"
  file_name = "pet-snippet.toml"
  public = false
  auto_sync = false
